### ISSUE TITLE
datacentersGet returns nothing

### ISSUE THREAD

**Issue by DanielRuf** [ionos-cloud/sdk-nodejs#6]
## Description
I have wondered why DataCentersApi.datacentersGet() did nothing and returns nothing.

`dcApi.datacentersGet().then((response: any, error: any) => log.debug(error));`

SDK version:
```
6.1.1
```
## How to Reproduce
```
            // initialize new SDK instance
            const dcApi = new sdk.DataCentersApi(sdkConfig);
            dcApi.datacentersGet().then((response: any) => log.debug(error));
```

**Comment by DanielRuf** [comment]
Trying some workarounds. Closing until I can provide a simple reproducible test case.

**Comment by DanielRuf** [comment]
Resolved, we had to use import instead of require. Maybe you want to extend the documentation with `import * as sdk from '@ionos-cloud/sdk-nodejs';`

**Comment by mimihalescu** [comment]
Hello! Thank you for bringing this up! We'll do some tests on ES6 projects too and update the documentation where needed.
